export let PropertyList = [
  {
    id: 0,
    ownerId: 0,
    title: "Apple",
    description: "🍎",
    status: "For Rent",
    route: "apple",
    price: 1900,
    extraDetails: [
      "Minimum rental period is three months",
      "Rental inclusive utilities, wifi and apartment common area cleaning",
    ],
    maxPax: 2,
    roomFeatures: ["Room Feature 1", "Room Feature 2"],
  },
  {
    id: 1,
    ownerId: 0,
    title: "Banana",
    description: "🍌",
    status: "For Sale",
    route: "banana",
    price: 1900,
    extraDetails: [
      "Minimum rental period is three months",
      "Rental inclusive utilities, wifi and apartment common area cleaning",
    ],
    maxPax: 2,
    roomFeatures: ["Room Feature 1", "Room Feature 2"],
  },
  {
    id: 2,
    ownerId: 1,
    title: "Orange",
    description: "🍊",
    status: "For Rent",
    route: "orange",
    price: 1900,
    extraDetails: [
      "Minimum rental period is three months",
      "Rental inclusive utilities, wifi and apartment common area cleaning",
    ],
    maxPax: 2,
    roomFeatures: ["Room Feature 1", "Room Feature 2"],
  },
];
